import test from 'node:test';
import assert from 'node:assert/strict';
import { gridInfo, validateDomain, escapeHTML } from '../packages/kernel/src/index.js';
import { NODE_TYPES, createNode, validateDocument, topologicalOrder, connect, autoLayout, downstream } from '../packages/graph/src/index.js';
import { DocumentStore, serializeProject, parseProject } from '../packages/document/src/index.js';
import { compileCPU, compileDocument } from '../packages/compile/src/index.js';
import { sampleVolume, gradient, sdBox, sdCylinder, sdEllipsoid, smoothUnion } from '../packages/field/src/index.js';
import { tpms, cubicLattice, octetLattice } from '../packages/lattice/src/index.js';
import { EXAMPLES } from '../app/examples.js';
import { document, node, close, domain } from './helpers.mjs';
test('Domain bounds and x-fast nodal grid contract', () => { const g = gridInfo(domain, 21); assert.equal(g.count, 9261); assert.deepEqual(g.step, [1, 1, 1]); assert.throws(() => gridInfo(domain, 3)); assert.throws(() => validateDomain({ min: [0, 0, 0], max: [1, 0, 1] })); });
test('HTML escaping rejects markup injection', () => { assert.equal(escapeHTML('<script>"&\''), '&lt;script&gt;&quot;&amp;&#39;'); });
test('Primitive distances and analytic normals', () => { close(sdBox(0, 0, 0, 10, 8, 6, 2), -6); close(sdBox(10, 0, 0, 10, 8, 6, 2), 0); close(sdCylinder(0, 0, 0, 4, 9), -4); close(sdEllipsoid(0, 0, 0, 2, 3, 4), -2); close(sdEllipsoid(2, 0, 0, 2, 3, 4), 0); close(smoothUnion(0, 0, 4), -1); assert.deepEqual(gradient((x, y, z) => Math.hypot(x, y, z) - 5, 5, 0, 0), [1, 0, 0]); });
test('Trilinear volume sampling reproduces an affine field', () => { const n = 4, values = Float32Array.from({ length: 64 }, (_, i) => i % n + 2 * (Math.floor(i / n) % n) + 3 * Math.floor(i / n / n)); close(sampleVolume(values, n, [0, 0, 0], [3, 3, 3], .25, 1.1, 2.4), 9.65); });
test('Node construction preserves unspecified defaults', () => { const b = createNode('box', { params: { radius: 2 } }); assert.deepEqual(b.params.size, [48, 38, 42]); assert.equal(b.params.radius, 2); });
test('Typed connections, cycle rejection, rollback and unknown port rejection', () => { const a = node('sphere'), b = node('translate'), c = node('translate'), field = node('constant'); const d = document([a, b, c, field], a.id); connect(d, b.id, 'body', a.id); connect(d, c.id, 'body', b.id); assert.throws(() => connect(d, b.id, 'body', c.id), /Cyclic/); assert.equal(b.inputs.body, a.id); assert.throws(() => connect(d, b.id, 'body', field.id), /requires body/); assert.throws(() => connect(d, b.id, 'bogus', a.id), /Unknown input/); assert.deepEqual([...downstream(d, a.id)].sort(), [a.id, b.id, c.id].sort()); });
test('Incomplete editable blocks are allowed but reachable compilation is strict', () => { const a = node('union'), d = document([a]); validateDocument(d); assert.throws(() => compileCPU(d), /connect/); });
test('Snapshot transactions undo redo coalescing and invalid mutation rollback', () => { const a = node('sphere', { radius: 4 }), store = new DocumentStore(document([a])); store.transact('Drag', d => d.nodes[0].params.radius = 5, { mergeKey: 'radius' }); store.transact('Drag', d => d.nodes[0].params.radius = 6, { mergeKey: 'radius' }); assert.equal(store.history.length, 1); store.undo(); assert.equal(store.value.nodes[0].params.radius, 4); store.redo(); assert.equal(store.value.nodes[0].params.radius, 6); assert.throws(() => store.transact('Invalid', d => d.nodes[0].params.radius = -1)); assert.equal(store.value.nodes[0].params.radius, 6); });
test('Project roundtrip and schema rejection', () => { const d = EXAMPLES[0].make(); assert.deepEqual(parseProject(serializeProject(d)), d); assert.throws(() => parseProject('{"version":4}')); const c = structuredClone(d); c.nodes[0].id = '<bad>'; assert.throws(() => validateDocument(c)); });
test('Shader program keys exclude numeric values but include graph structure', () => { const a = node('sphere', { radius: 4 }), d = document([a]), p = compileDocument(d); a.params.radius = 5; const q = compileDocument(d); assert.equal(p.key, q.key); assert.notDeepEqual(p.parameters, q.parameters); const b = node('shell', {}, { body: a.id }); d.nodes.push(b); d.root = b.id; assert.notEqual(q.key, compileDocument(d).key); assert.equal(q.sample(0, 0, 0), -5); });
test('Translate, rotate, scale, booleans and shell behavior', () => { const a = node('box', { size: [8, 2, 2], radius: 0 }), b = node('rotate', { angles: [0, 0, 90] }, { body: a.id }), c = node('translate', { offset: [5, 0, 0] }, { body: b.id }), d = document([a, b, c]); const f = compileCPU(d); assert.ok(f(5, 3, 0) < 0); assert.ok(f(8, 0, 0) > 0); const s = node('sphere', { radius: 3 }), shell = node('shell', { thickness: 1 }, { body: s.id }); const g = compileCPU(document([s, shell])); close(g(0, 0, 0), 2.5); close(g(3, 0, 0), -.5); });
test('Field bindings alter geometric occupancy, not just display color', () => { const r = node('constant', { value: 7 }), s = node('sphere', { radius: 2 }, { radius: r.id }), f = compileCPU(document([r, s])); close(f(6, 0, 0), -1); });
test('Finite repetition has exactly the requested centred copies', () => { const a = node('sphere', { radius: 1 }), b = node('repeat', { spacing: [5, 5, 5], count: [3, 1, 1] }, { body: a.id }), f = compileCPU(document([a, b])); for (const x of [-5, 0, 5])
    assert.ok(f(x, 0, 0) < 0); assert.ok(f(10, 0, 0) > 0); });
for (const family of ['gyroid', 'schwarz', 'diamond', 'neovius'])
    test(`${family} is periodic and its wall interval expands monotonically`, () => { const a = tpms(family, 1.7, 2.3, -3.1, 11, .5); close(tpms(family, 12.7, 2.3, -3.1, 11, .5), a, 1e-10); assert.ok(tpms(family, 1.7, 2.3, -3.1, 11, 1) < a); });
test('Beam lattice centre distances', () => { close(cubicLattice(0, 0, 0, 10, .8), -.8); close(octetLattice(0, 0, 0, 10, .8), -.8); });
for (const [type, def] of Object.entries(NODE_TYPES))
    test(`Kernel coverage: ${type}`, () => { const body = node('box'), field = node('constant'), target = node(type), d = document([body, field, target], def.output === 'body' ? target.id : body.id); for (const [key, port] of Object.entries(def.inputs))
        if (port.required)
            target.inputs[key] = port.type === 'body' ? body.id : field.id; if (type === 'volume') {
        target.params.asset = 'test';
        d.assets.test = { n: 4, min: [-10, -10, -10], max: [10, 10, 10], data: Array.from({ length: 64 }, (_, i) => Math.hypot(i % 4 - 1.5, Math.floor(i / 4) % 4 - 1.5, Math.floor(i / 16) - 1.5) - 1) };
    } validateDocument(d); const p = compileDocument(d, target.id, def.output === 'scalar' ? target.id : null); assert.ok(p.wgsl.includes('fn scene')); assert.ok(p.glsl.includes('float scene')); assert.ok(!p.glsl.includes('fn ')); for (const point of [[0, 0, 0], [1.37, -2.71, 3.43], [20, 30, 40]])
        assert.ok(Number.isFinite(p.sample(...point)), `${type} is finite`); });
for (const example of EXAMPLES)
    test(`Example compiles and lays out: ${example.id}`, () => { const d = example.make(); validateDocument(d); autoLayout(d); const p = compileDocument(d); assert.ok(Number.isFinite(p.sample(2.1, -3.7, 4.2))); assert.equal(new Set(topologicalOrder(d, null, false).map(n => n.id)).size, d.nodes.length); });
test('Compiled CPU closures retain the same parameter snapshot as GPU buffers', () => { const s = node('sphere', { radius: 4 }), d = document([s]), p = compileDocument(d); s.params.radius = 12; close(p.sample(0, 0, 0), -4); close(p.parameters[0], 4); });
test('Volume assets are immutable and structurally shared through history', () => { const v = node('volume', { asset: 'v' }), d = document([v]); d.assets.v = { n: 4, min: [-1, -1, -1], max: [1, 1, 1], data: new Float32Array(64).fill(1) }; const store = new DocumentStore(d), asset = store.value.assets.v; store.transact('Rename', x => x.name = 'Changed'); assert.equal(store.value.assets.v, asset); assert.throws(() => store.transact('Unsafe', x => x.assets.v.data[0] = 2), TypeError); store.transact('Replace volume', x => x.assets.v = { ...x.assets.v, data: new Float32Array(64).fill(2) }); assert.notEqual(store.value.assets.v, asset); store.undo(); assert.equal(store.value.assets.v, asset); });
test('Engineering units and finite display properties are validated', () => { const d = document([node('sphere')]); assert.throws(() => validateDocument({ ...d, units: 'inch' })); assert.throws(() => validateDocument({ ...d, view: { color: [NaN, 0, 0] } })); });
